import type { Metadata } from 'next';
import '../globals.css';
import Navbar from '@/components/global/Navbar';
import Footer from '@/components/global/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {children}
      <Footer />
    </>
  );
}
